name: 🧪 Cargo Tests
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*.rs'
      - 'examples/**/*'
      - 'ort-sys/**/*.rs'
      - 'ort-sys/**/dist.txt'
      - 'build.rs'
      - 'Cargo.toml'
      - '.cargo/**/*'
      - 'tests/**/*'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*.rs'
      - 'examples/**/*'
      - 'ort-sys/**/*.rs'
      - 'ort-sys/**/dist.txt'
      - 'build.rs'
      - 'Cargo.toml'
      - '.cargo/**/*'
      - 'tests/**/*'
env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
          - os: ubuntu-24.04-arm
          - os: windows-latest
          - os: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.7.8
      - name: Run tests
        run: |
          cargo test -p ort --verbose --features fetch-models,tls-rustls -- --test-threads 1
        env:
          RUSTFLAGS: ${{ startsWith(matrix.platform.os, 'macos') && '-Clink-arg=-fapple-link-rtlib' || '' }}
          RUSTDOCFLAGS: ${{ startsWith(matrix.platform.os, 'macos') && '-Clink-arg=-fapple-link-rtlib' || '' }}
